pool:
  vmImage: 'vs2017-win2017'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  displayName: 'install yarn'

- script: |
    yarn install
  displayName: 'yarn install'

- script: |
    yarn ci
  displayName: 'yarn ci'
